# Generated by Django 4.1.4 on 2023-01-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user'], 'verbose_name': 'Perfil reistrado', 'verbose_name_plural': 'Perfiles registrados'},
        ),
    ]
