# Generated by Django 4.1.4 on 2023-01-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humedad_exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hum', models.CharField(max_length=2)),
                ('dia_hora_leida', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Humedad exterior',
                'verbose_name_plural': 'Humedad exterior',
                'get_latest_by': 'dia_hora_leida',
            },
        ),
        migrations.CreateModel(
            name='Humedad_piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojado', models.CharField(max_length=1)),
                ('dia_hora_leida', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Humedad del suelo',
                'verbose_name_plural': 'Humedad del suelo',
                'get_latest_by': 'dia_hora_leida',
            },
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=2)),
                ('hum', models.CharField(max_length=2)),
                ('presencia', models.CharField(max_length=1)),
                ('lum_1', models.CharField(max_length=3)),
                ('lum_2', models.CharField(max_length=3)),
                ('seg_puerta', models.CharField(max_length=1)),
                ('AC_1', models.CharField(max_length=1)),
                ('AC_2', models.CharField(max_length=1)),
                ('dia_hora_leida', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Interior del laboratorio',
                'verbose_name_plural': 'Interior del laboratorio',
                'get_latest_by': 'dia_hora_leida',
            },
        ),
        migrations.CreateModel(
            name='Temperatura_exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=2)),
                ('dia_hora_leida', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Temperatura exterior',
                'verbose_name_plural': 'Temperatura exterior',
                'get_latest_by': 'dia_hora_leida',
            },
        ),
    ]
