# Generated by Django 4.1.4 on 2023-02-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_promedio_humedad_promedio_luminosidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promedio_luminosidad',
            name='lum_object',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
